### ISSUE TITLE
KeyError: 90 when running the main.py file

### ISSUE THREAD

**Issue by eurotransient** [Mijago/D2StatGenerator#3]
I've been using D2StatGenerator pretty regularly since it was put up here, but at some point it stopped working for me and I can't quite figure out why.

When I try to run it, I get a KeyError: 90 that dumps me back to the command line. Here's the traceback in the terminal leading up to that:

```
Traceback (most recent call last):
  File "E:\OneDrive\Documents\GitHub\D2StatGenerator\main.py", line 71, in <module>
    report.generate(data).save()
  File "E:\OneDrive\Documents\GitHub\D2StatGenerator\app\reports\KDReport.py", line 21, in generate
    df = self.generateDataframe(data)
  File "E:\OneDrive\Documents\GitHub\D2StatGenerator\app\reports\KDReport.py", line 88, in generateDataframe
    df = self.generateRawDataframe(data)
  File "E:\OneDrive\Documents\GitHub\D2StatGenerator\app\reports\KDReport.py", line 70, in generateRawDataframe
    mode_name.append(self.manifest.ActivityTypeNames[datapoint["activityDetails"]["mode"]])
KeyError: 90
PS E:\OneDrive\Documents\GitHub\D2StatGenerator>
```

I'm not quite sure what the issue is, but my suspicion is there's a new mode type with a value of 90 that was added -- Rift perhaps?

That said, I'm not sure what I could do to update this.

**Comment by Mijago** [comment]
Check out one of the two pull requests, I just didn't have the time yet.
